export type Level = "A1" | "A2" | "B1" | "B2" | "C1";
export interface Question {
  id: number; question: string; options: string[]; correctAnswer: string;
  level: Level; topic: string; explanation: string;
}
// Row: [topic, question, correct, wrong1, wrong2, wrong3, explanation]
type Row = [string, string, string, string, string, string, string];

const RAW: Record<Level, Row[]> = {
  A1: [
    ["grammar", "She ___ a teacher.", "is", "are", "am", "be", "С she используем is."],
    ["articles", "I have ___ apple.", "an", "a", "the", "two", "Перед гласным звуком — an."],
    ["vocabulary", "What is the opposite of “big”?", "small", "tall", "long", "fast", "Big — small."],
    ["grammar", "They ___ from Spain.", "are", "is", "am", "be", "С they — are."],
    ["prepositions", "The book is ___ the table.", "on", "at", "to", "of", "On — на поверхности."],
    ["grammar", "___ you like pizza?", "Do", "Does", "Are", "Is", "Present Simple с you — Do."],
    ["tenses", "He ___ coffee every morning.", "drinks", "drink", "drinking", "drinked", "С he/she/it глагол + s."],
    ["vocabulary", "Which number comes after nine?", "ten", "eight", "eleven", "seven", "9 → 10."],
    ["grammar", "This is my sister. ___ name is Anna.", "Her", "His", "She", "Hers", "Her — притяжательное для she."],
    ["grammar", "There ___ two cats in the garden.", "are", "is", "am", "be", "Множественное число — are."],
    ["vocabulary", "We eat breakfast in the ___.", "morning", "evening", "afternoon", "night", "Завтрак — утром."],
    ["grammar", "I ___ tired today.", "am", "is", "are", "be", "С I — am."],
    ["sentence structure", "Choose the correct sentence.", "I don't like tea.", "I no like tea.", "I not like tea.", "I doesn't like tea.", "Отрицание: don't + глагол."],
    ["grammar", "One child, two ___.", "children", "childs", "childes", "childrens", "Неправильное множественное число."],
    ["prepositions", "I go to school ___ bus.", "by", "with", "at", "to", "By bus — на автобусе."],
    ["grammar", "What ___ your name?", "is", "are", "do", "does", "Your name — is."],
    ["vocabulary", "A person who teaches is a ___.", "teacher", "doctor", "driver", "cook", "Teacher — учитель."],
    ["tenses", "We ___ football on Sundays.", "play", "plays", "playing", "are play", "С we — play."],
    ["modal verbs", "Can she ___ English?", "speak", "speaks", "speaking", "to speak", "После can — глагол без to."],
    ["common usage", "It is ___ hot today.", "very", "much", "many", "a lot of", "Very + прилагательное."],
  ],
  A2: [
    ["tenses", "Yesterday I ___ to the cinema.", "went", "go", "goed", "going", "Past Simple от go — went."],
    ["grammar", "She is ___ than her brother.", "taller", "tall", "more tall", "tallest", "Сравнительная степень: taller."],
    ["grammar", "I'm ___ to visit London next summer.", "going", "go", "will going", "went", "Be going to — план."],
    ["grammar", "How ___ water do you drink?", "much", "many", "few", "lot", "Water неисчисляемое — much."],
    ["tenses", "We ___ TV when the phone rang.", "were watching", "watch", "are watching", "have watched", "Past Continuous — процесс в прошлом."],
    ["modal verbs", "You ___ wear a seat belt. It's the law.", "must", "can", "would", "could", "Must — обязанность."],
    ["perfect tenses", "I've ___ finished my homework.", "just", "yet", "ago", "since", "Just — только что."],
    ["grammar", "There isn't ___ milk in the fridge.", "any", "some", "a", "many", "В отрицании — any."],
    ["grammar", "This is the ___ film I've ever seen.", "best", "better", "good", "most good", "Превосходная степень: the best."],
    ["prepositions", "The meeting is ___ 3 o'clock.", "at", "in", "on", "by", "At + время."],
    ["conditionals", "If it rains, we ___ at home.", "will stay", "would stay", "stayed", "are staying", "Первый тип: if + Present, will."],
    ["vocabulary", "Can I ___ your pen, please?", "borrow", "lend", "rent", "spend", "Borrow — взять на время."],
    ["grammar", "He didn't ___ the answer.", "know", "knew", "known", "knows", "После didn't — инфинитив."],
    ["perfect tenses", "___ you ever been to Paris?", "Have", "Did", "Are", "Do", "Have you ever been — Present Perfect."],
    ["phrasal verbs", "I usually ___ up at 7.", "get", "take", "put", "do", "Get up — вставать."],
    ["prepositions", "She lives ___ a small town.", "in", "on", "at", "to", "In + город."],
    ["vocabulary", "The opposite of “expensive” is ___.", "cheap", "slow", "poor", "empty", "Expensive — cheap."],
    ["sentence structure", "He asked me ___ I was from.", "where", "what", "who", "which", "Косвенный вопрос: where."],
    ["perfect tenses", "We have lived here ___ 2019.", "since", "for", "from", "during", "Since + точка во времени."],
    ["grammar", "Would you like ___ tea?", "some", "any", "a", "many", "В предложении — some."],
  ],
  B1: [
    ["conditionals", "If I ___ more time, I would learn Spanish.", "had", "have", "will have", "would have", "Второй тип: if + Past Simple."],
    ["perfect tenses", "I've been waiting here ___ two hours.", "for", "since", "during", "from", "For + период времени."],
    ["passive", "The book ___ by millions of people.", "was read", "reads", "was reading", "had read", "Страдательный залог: was + V3."],
    ["reported speech", "She said she ___ tired.", "was", "is", "would", "had", "Согласование времён: is → was."],
    ["modal verbs", "You ___ smoke here. It's forbidden.", "mustn't", "don't have to", "needn't", "wouldn't", "Mustn't — запрет."],
    ["grammar", "I'm not used to ___ up so early.", "getting", "get", "got", "to get", "Be used to + -ing."],
    ["phrasal verbs", "Please ___ the light; it's too dark.", "turn on", "turn up", "turn in", "turn over", "Turn on — включить."],
    ["perfect tenses", "By the time we arrived, the film ___.", "had started", "started", "has started", "was starting", "Past Perfect — раньше другого события."],
    ["grammar", "He's the man ___ car was stolen.", "whose", "who", "which", "that", "Whose — чей."],
    ["grammar", "I wish I ___ speak French.", "could", "can", "will", "would", "Wish + could."],
    ["grammar", "She suggested ___ to the beach.", "going", "to go", "go", "went", "Suggest + -ing."],
    ["grammar", "I enjoy ___ novels in the evening.", "reading", "to read", "read", "reads", "Enjoy + -ing."],
    ["vocabulary", "The company wants someone with relevant ___.", "experience", "experiences", "experienced", "experiencing", "Experience в значении «опыт» — неисчисляемое."],
    ["conditionals", "Unless you hurry, you ___ the train.", "will miss", "miss", "would miss", "missed", "Unless + Present, will."],
    ["grammar", "I look forward to ___ from you.", "hearing", "hear", "heard", "to hear", "Look forward to + -ing."],
    ["prepositions", "He's very good ___ solving problems.", "at", "in", "on", "for", "Good at."],
    ["grammar", "The meal was ___ delicious that we ate everything.", "so", "such", "too", "very", "So + прил. + that."],
    ["modal verbs", "You had ___ see a doctor.", "better", "good", "best", "rather", "Had better — лучше бы."],
    ["sentence structure", "It was raining, ___ we stayed inside.", "so", "because", "but", "although", "So — следствие."],
    ["phrasal verbs", "I can't ___ what this word means.", "figure out", "figure on", "figure in", "figure at", "Figure out — разобраться."],
  ],
  B2: [
    ["conditionals", "If I ___ harder, I would have passed the exam.", "had studied", "studied", "would study", "have studied", "Третий тип: if + Past Perfect."],
    ["modal verbs", "There's no sign of Tom. He ___ left already.", "may have", "can have", "shall have", "could to", "May have + V3 — предположение о прошлом."],
    ["sentence structure", "Hardly ___ arrived when it started to rain.", "had we", "we had", "did we", "have we", "Инверсия после hardly."],
    ["grammar", "The project, ___ was delayed, is now finished.", "which", "that", "what", "who", "В неопределённом придаточном — which."],
    ["phrasal verbs", "We've run ___ of milk.", "out", "off", "away", "down", "Run out of — закончиться."],
    ["prepositions", "He apologised ___ being late.", "for", "about", "of", "to", "Apologise for."],
    ["grammar", "I'd rather you ___ tell anyone.", "didn't", "don't", "won't", "haven't", "Would rather + Past Simple."],
    ["perfect tenses", "By next year, she ___ here for ten years.", "will have worked", "will work", "has worked", "works", "Future Perfect."],
    ["phrasal verbs", "The manager turned ___ my request.", "down", "off", "up", "over", "Turn down — отклонить."],
    ["common usage", "___ the rain, we went for a walk.", "Despite", "Although", "However", "Because", "Despite + существительное."],
    ["sentence structure", "Not only ___ late, but he also forgot the documents.", "was he", "he was", "did he", "he did", "Инверсия после not only."],
    ["grammar", "I regret ___ you that the flight is cancelled.", "to tell", "telling", "tell", "told", "Regret to tell — с сожалением сообщаю."],
    ["prepositions", "She insisted ___ paying for dinner.", "on", "in", "at", "to", "Insist on."],
    ["grammar", "The results were ___ than we had expected.", "far better", "more better", "much good", "best", "Far + сравнительная степень."],
    ["grammar", "It's high time we ___ a decision.", "made", "make", "will make", "had to make", "It's high time + Past Simple."],
    ["grammar", "He denied ___ the window.", "breaking", "to break", "break", "to breaking", "Deny + -ing."],
    ["conditionals", "Had I known, I ___ differently.", "would have acted", "would act", "had acted", "acted", "Инверсия третьего типа."],
    ["vocabulary", "We need to ___ the problem before it gets worse.", "tackle", "catch", "hold", "reach", "Tackle a problem — решать проблему."],
    ["common usage", "She's ___ the most talented person I know.", "by far", "far by", "by long", "very", "By far the most — намного."],
    ["passive", "The company is said ___ losing money.", "to be", "be", "being", "to been", "Is said to be + -ing."],
  ],
  C1: [
    ["conditionals", "___ I to lose my job, I'd have to sell the house.", "Were", "Should", "If", "Had", "Формальная инверсия: Were I to…"],
    ["sentence structure", "Seldom ___ such a beautiful sunset.", "have I seen", "I have seen", "I saw", "have seen I", "Инверсия после seldom."],
    ["grammar", "The report, ___ conclusions were controversial, was widely criticised.", "whose", "who's", "which", "that", "Whose — притяжательное относительное."],
    ["grammar", "It's essential that he ___ present at the meeting.", "be", "is", "will be", "was", "Сослагательное наклонение: be."],
    ["vocabulary", "The evidence was ___; nobody could doubt it.", "irrefutable", "unreliable", "ambiguous", "dubious", "Irrefutable — неопровержимый."],
    ["common usage", "She's ___ her mother's footsteps by becoming a surgeon.", "following in", "going after", "coming in", "walking", "Follow in someone's footsteps."],
    ["sentence structure", "No sooner had he sat down ___ the phone rang.", "than", "when", "then", "that", "No sooner … than."],
    ["conditionals", "I would have called you had I ___ your number.", "known", "know", "knew", "have known", "Had I known — инверсия."],
    ["vocabulary", "He's a ___ speaker; everyone listens spellbound.", "compelling", "compulsory", "compelled", "compulsive", "Compelling — захватывающий."],
    ["prepositions", "The proposal was rejected ___ the grounds of cost.", "on", "at", "by", "for", "On the grounds of."],
    ["sentence structure", "Little ___ she know that the surprise was planned.", "did", "was", "has", "would", "Инверсия после little."],
    ["vocabulary", "The team managed to ___ the deadline despite setbacks.", "meet", "catch", "touch", "approach", "Meet a deadline."],
    ["common usage", "___ from the fact that it's expensive, the car is unreliable.", "Apart", "Except", "Outside", "Away", "Apart from."],
    ["grammar", "I wish I ___ so rude to her yesterday.", "hadn't been", "wasn't", "weren't", "wouldn't be", "Сожаление о прошлом: wish + Past Perfect."],
    ["grammar", "The manager, along with her assistants, ___ attending the conference.", "is", "are", "were", "have", "Подлежащее — the manager."],
    ["prepositions", "The film is reminiscent ___ early Hitchcock.", "of", "to", "with", "from", "Reminiscent of."],
    ["phrasal verbs", "I can't put ___ with his rudeness any longer.", "up", "on", "in", "off", "Put up with — мириться."],
    ["sentence structure", "Rarely does one come across ___ dedicated a teacher.", "so", "such", "too", "very", "So + прил. + a + сущ."],
    ["common usage", "The CEO's remarks were taken ___ context.", "out of", "off", "away from", "without", "Take out of context."],
    ["vocabulary", "Which word means “to fall suddenly and steeply”?", "plummet", "soar", "fluctuate", "stagnate", "Plummet — резко падать."],
  ],
};

export const QUESTIONS: Question[] = [];
(Object.keys(RAW) as Level[]).forEach((level) =>
  RAW[level].forEach(([topic, question, correct, w1, w2, w3, explanation]) =>
    QUESTIONS.push({ id: QUESTIONS.length + 1, question, options: [correct, w1, w2, w3], correctAnswer: correct, level, topic, explanation })
  )
);
